version: '3'

services:
  blue:
    restart: on-failure
    build:
      context: .
      dockerfile: .build/docker/Dockerfile.blue.api
    container_name: blue
    volumes:
      - ./app/blue:/app
    ports:
      - 8000:8000

  green:
    restart: on-failure
    build:
      context: .
      dockerfile: .build/docker/Dockerfile.green.api
    container_name: green
    volumes:
      - ./app/green:/app
    ports:
      - 8001:8000

  nginx:
    build:
      context: .
      dockerfile: .build/docker/Dockerfile.nginx
    container_name: nginx
    ports:
      - 80:80
    depends_on:
      - blue
      - green

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - .config/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 9090:9090

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3000:3000

networks:
  default:
    name: api_gateway
